// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeHU0NdwpZYAOhXvt2RxXVHDkrX99hgYs',
    appId: '1:456049447702:web:30e54318a8efbed2357637',
    messagingSenderId: '456049447702',
    projectId: 'jewelsmart-231fb',
    authDomain: 'jewelsmart-231fb.firebaseapp.com',
    storageBucket: 'jewelsmart-231fb.firebasestorage.app',
    measurementId: 'G-67G1L3C7H6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCqboVlTKaofY6kHA3QlQRyQpxXFpTVxg',
    appId: '1:456049447702:android:aa87a24f6b1a51c8357637',
    messagingSenderId: '456049447702',
    projectId: 'jewelsmart-231fb',
    storageBucket: 'jewelsmart-231fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiugwi4mu5YGSwxk7MPy11t0KyjzP9zmk',
    appId: '1:456049447702:ios:9ee75ed3702f6245357637',
    messagingSenderId: '456049447702',
    projectId: 'jewelsmart-231fb',
    storageBucket: 'jewelsmart-231fb.firebasestorage.app',
    androidClientId: '456049447702-8cu1jtf16ascjlf1lqduap1q1tmjeei3.apps.googleusercontent.com',
    iosClientId: '456049447702-m0703hm079tmakpcniftdguid5jiakph.apps.googleusercontent.com',
    iosBundleId: 'com.example.jewelsmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiugwi4mu5YGSwxk7MPy11t0KyjzP9zmk',
    appId: '1:456049447702:ios:9ee75ed3702f6245357637',
    messagingSenderId: '456049447702',
    projectId: 'jewelsmart-231fb',
    storageBucket: 'jewelsmart-231fb.firebasestorage.app',
    iosBundleId: 'com.example.jewelsmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeHU0NdwpZYAOhXvt2RxXVHDkrX99hgYs',
    appId: '1:456049447702:web:5ef777da145d36e5357637',
    messagingSenderId: '456049447702',
    projectId: 'jewelsmart-231fb',
    authDomain: 'jewelsmart-231fb.firebaseapp.com',
    storageBucket: 'jewelsmart-231fb.firebasestorage.app',
    measurementId: 'G-7L080TR01W',
  );
}